apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-infra
resources:
  - namespace.yaml
  - api-gateway.yaml
  - model-registry-service.yaml
  - deployment-manager-service.yaml
  - model-router-service.yaml
  - history-service.yaml
  - timeseries-inference-service.yaml
